name: Latest blog post workflow
on:
  schedule:
    # 每 24 小時執行一次
    - cron: '0 0 * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in hexo posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://eva813.github.io/atom.xml"
          max_post_count: 5
          comment_tag_name: "BLOG-POST-LIST"